---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iptnetflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iptnetflow
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["monitoring.coreos.com"]
  resourceNames: ["main","longterm"]
  resources: ["prometheuses/http"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iptnetflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iptnetflow
subjects:
  - kind: ServiceAccount
    name: iptnetflow-sa
    namespace: iptnetflow
